name: Update feed snippet

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false # This is important if you have branch protection rules!
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.PRIVATE_REPO_SSH_KEY }}

    - name: Import bot's GPG key for signing commits
      id: import-gpg
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.BOT_GPG_PASSPHRASE }}

    - uses: actions/setup-go@v5
      id: setup-go
      with:
        go-version-file: ./go.mod

    - name: Install feedsnippet
      run: go install github.com/ikawaha/feedsnippet@latest

    - name: Update README.md
      run: feedsnippet -config feedsnippet.yml -diff -file README.md -verbose

    - name: git commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
        GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
        GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
        GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
      run: |
        git remote set-url origin git@github.com:phoepsilonix/phoepsilonix.git
        git log -1
        git add README.md
        git diff --cached --quiet || (git commit -m "Update feed snippet" && git push origin main)
